#!/bin/sh

echo "aclocal ..."
aclocal && (
    echo "autoheader ..."
    autoheader && (
	echo "autoconf ..."
	autoconf && (
	    echo "libtoolize --automake --force ..."
	    libtoolize --automake --force && (
		echo "automake --add-missing"
		automake --add-missing 
	    )
	)
    )
)
