#!/bin/bash

echo "Running aclocal..."
aclocal

[ ! $? -eq 0 ] && exit

echo "Running autoheader..."
autoheader

[ ! $? -eq 0 ] && exit

echo "Running autoconf..."
autoconf

[ ! $? -eq 0 ] && exit

echo "Running automake --add-missing..."
automake --add-missing
