.\"						Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH fsck.reiser4 8 "07 May, 2003" reiser4progs "reiser4progs manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fsck.reiser4 \- the program for checking and repairing reiser4 filesystem.
.SH SYNOPSIS
.B fsck.reiser4
[ options ] FILE
.SH DESCRIPTION
.B fsck.reiser4
is reiser4 filesystem check and repair program.
.SH COMMON OPTIONS
.TP
.B -V, --version
prints program version
.TP
.B -?, -h, --help
prints program help
.TP
.B -q, --quiet
forces fsck to be working without any questions
.TP
.B -a, -p, --auto, --preen
automatically checks the file system without any questions
.TP
.B -v, --verbose
makes fsck to be verbose.
.TP
.B -f, --force
makes fsck to use whole disk, not block device or mounted partition.
.SH CHECK OPTIONS
.TP
.B -l, --logfile
complains into the logfile
.TP
.B --check
consistency checking (default)
.TP
.B --fixable
fixes what can be fixed without rebuild
.TP
.B --rebuild
fixes all fs corruptions
.RS
.SH REPORTING BUGS
Report bugs to <vitaly@namesys.com>, <reiserfs-list@namesys.com>
.SH SUPPORT
You can get support at http://www.namesys.com/support.html
.SH SEE ALSO
.BR libreiser4(8),
.BR debugfs.reiser4(8),
.BR mkfs.reiser4(8),
.BR measurefs.reiser4(8)
.BR cpfs.reiser4(8)
.BR resizefs.reiser4(8)
.SH AUTHOR
This manual page was written by Vitaly Fertman <vitaly@namesys.com>
