.\"						Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH mkfs.reiser4 8 "02 Oct, 2002" reiser4progs "reiser4progs manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mkfs.reiser4 \- the program for creating reiser4 filesystem.
.SH SYNOPSIS
.B mkfs.reiser4
[ options ] FILE1 FILE2 ... [ size[K|M|G] ]
.SH DESCRIPTION
.B mkfs.reiser4
is reiser4 filesystem creation program. It is based on new libreiser4 library. Since libreiser4 fully plugin-based, we have potential possibility to create not just reiser4, but any filesystem or database format, which based on the balanced tree.
.SH COMMON OPTIONS
.TP
.B -V, --version
prints program version
.TP
.B -?, -u, --usage
prints program usage
.TP
.B -q, --quiet
forces creating filesystem without any questions
.TP
.B -f, --force
makes mkfs to use whole disk, not block device or mounted partition.
.SH MKFS OPTIONS
.TP
.B -b, --block-size N
block size to be used (4096 only at the moment)
.TP
.B -l, --label LABEL
volume label to be used
.TP
.B -i, --uuid UUID
universally unique identifier to be used
.TP
.B -s, --lost-found
forces mkfs to create lost+found directory.
.TP
.B -k, --keys=LARGE|SHORT
key length to be used in filesystem. By default LARGE is used. It
contains one more component, called "ordering" and needed for making
files data lie in the readdir() order. This improves file access time,
but makes creation time worse.
.SH PLUGIN OPTIONS
.TP
.B -P, --known-plugins
prints known plugins.
.TP
.B -o, --override TYPE=PLUGIN, ...
overrides the default plugin of the type "TYPE" by the plugin "PLUGIN"
.sp 1
Examples:
.sp 1
mkfs.reiser4 -qf -o nodeptr=nodeptr41,hash=rupasov_hash /dev/hda2
.RS
.SH REPORTING BUGS
Report bugs to <umka@namesys.com>, <reiserfs-list@namesys.com>
.SH SUPPORT
You can get support at http://www.namesys.com/support.html
.SH SEE ALSO
.BR libreiser4(8),
.BR measurefs.reiser4(8),
.BR debugfs.reiser4(8),
.BR fsck.reiser4(8)
.BR cpfs.reiser4(8)
.BR resizefs.reiser4(8)
.SH AUTHOR
This manual page was written by Yury Umanets <umka@namesys.com>

