.\"						Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH volume.reiser4 8 "16 Aug, 2020" reiser4progs "reiser4progs manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
volume.reiser4 \- the program for managing reiser4 logical volumes.
.SH SYNOPSIS
.B volume.reiser4
[ options ] [ FILE ] [ MNT ]
.SH DESCRIPTION
.B volume.reiser4
is a program to manage reiser4 logical (compound) volumes. It performs
operations on logical volumes like adding[removing] a brick to[from]
your volume, changing capacity of any brick of your volume, increasing
current upper limit on total number of bricks in your volume.
On-line options are applicable only to mounted volumes. Other options
don't have such restrictions. This program doesn't create initial volume.
Instead, it operates on bricks, which are formatted partitions. To
create a brick use mkfs.reiser4(8) utility.
.SH COMMON OPTIONS
.TP
.B -V, --version
prints program version.
.TP
.B -?, -h, --help
prints program help.
.TP
.B -y, --yes
assumes an answer 'yes' to all questions.
.SH OFF-LINE OPTIONS
.TP
.B -g, --register DEV
register a brick associated with device DEV in the system.
.TP
.B -u, --unregister DEV
unregister a brick associated with device DEV in the system.
.TP
.B -l, --list
print list of all bricks registered in the system.
.SH ON-LINE OPTIONS
.TP
.B -p, --print N
Print information about a brick of serial number N in the volume mounted at MNT.
.TP
.B -b, --balance
Balance volume mounted at MNT.
.TP
.B -z, --resize DEV
Change data capacity of a brick accociated with device DEV in the
volume mounted at MNT. The actual capacity has to be defined by the
option "-c (--capacity)".
.TP
.B -c, --capacity VALUE
define new data capacity VALUE for a device specified by option
"-z (--resize)".
.TP
.B -a, --add DEV
add a brick associated with device DEV to the volume mounted at MNT.
.TP
.B -x, --add-proxy
add a proxy brick associated with device DEV to the volume mounted at MNT.
.TP
.B -r, --remove
remove a brick associated with device DEV from the volume mounted at MNT.
.TP
.B -q, --scale N
increase 2^N times the upper limit for total number of bricks in the
volume mounted at MNT.
.TP
.B -m, --migrate
move all data blocks of regular FILE to a brick of serial number N.
.TP
.B -i, --set-immobile
set "immobile" property to regular FILE.
.TP
.B -e, --clear-immobile
clear "immobile" property of regular FILE.
.sp 1
.SH Examples:
.sp 1
To create a volume simply choose a volume ID and stripe size. Then create
a first brick, that will be meta-data brick of your volume:
.sp 1
VOL_ID=`uuidgen`
.sp 1
STRIPE=256K
.sp 1
mkfs.reiser4 -U $VOL_ID -t $STRIPE /dev/sdb1
.sp 1
To add a data brick to your initial volume mounted e.g. at /mnt simply
format some other block device (e.g. /dev/sdb2) with the same volume ID
and stripe size, then add it using option "-a":
.sp 1
mkfs.reiser4 -U $VOL_ID -t $STRIPE /dev/sdb2
.sp 1
volume.reiser4 -a /dev/sdb2 /mnt

.RS
.SH REPORTING BUGS
Report bugs to <reiserfs-devel@vger.kernel.org>
.SH SEE ALSO
.BR mkfs.reiser4(8),
.BR debugfs.reiser4(8),
.SH AUTHOR
This manual page was written by Edward Shishkin <edward.shishkin@gmail.com>
